TITEL = "3.6.1 Zusammenfassung & Reakkreditierungs-Empfehlung"

CONTENT = ("Diese Zusammenfassung bündelt die Ergebnisse der gesamten Analyse zum Verhältnis von Theorieanteil zu "
           "Anwendungsbezug im anwendungsorientierten Informatik-Bachelor der TH Köln. Sie fasst die Keep/Drop/Try-"
           "Bewertungen zusammen und leitet daraus konkrete Handlungsempfehlungen für die Reakkreditierung ab.\n\n"
           "Keep-Empfehlungen (Module, die beibehalten werden sollten): Algorithmik, AP1/AP2, Softwaretechnik I/II, "
           "Kommunikationstechnik & Netze, Einführungsprojekt Informatik, Praxissemester, Mensch-Computer-"
           "Interaktion. Diese Module zeigen eine gelungene Balance zwischen Theorie und Praxis und erfüllen ihren "
           "Anspruch als anwendungsorientierte Ausbildung.\n\n"
           "Try-Empfehlungen (Module, die verbessert werden sollten): Mathematik I/II (stärkere Verknüpfung mit "
           "informatischen Anwendungen), Theoretische Informatik I/II (stärkerer Praxisbezug, Integration moderner "
           "Compiler-Technologien), Datenbanken (Integration von NoSQL-Konzepten), Paradigmen der Programmierung "
           "(mehr Fokus auf praktische Anwendungen), Projektmanagement (stärkerer Fokus auf agile Methoden), "
           "Praxisprojekt mit Seminar (strukturiertere Betreuung), Künstliche Intelligenz (mehr praktische "
           "Übungen mit modernen Frameworks).\n\n"
           "Drop-Empfehlungen (Module, die überarbeitet werden müssen): Betriebssysteme & Rechnerarchitektur "
           "(Reduzierung der Hardware-Details, Fokus auf praktisch relevante Aspekte).\n\n"
           "Zusätzliche Empfehlungen: Die Szenarien 'Theorie-Turbo' und 'Praxis-Duales-Modell' zeigen Möglichkeiten "
           "auf, wie das Curriculum flexibler gestaltet werden könnte, um unterschiedliche Studierendengruppen "
           "besser zu bedienen. Eine differenzierte Betrachtung könnte helfen, sowohl theoretisch als auch "
           "praxisorientiert interessierte Studierende optimal zu fördern.\n\n"
           "Fazit: Der Studiengang erfüllt seinen Anspruch als anwendungsorientierter Bachelor grundsätzlich gut, "
           "hat aber in einigen Bereichen Verbesserungspotenzial. Die vorgeschlagenen Anpassungen würden die "
           "Balance zwischen Theorie und Praxis weiter optimieren und den Studiengang noch besser an die "
           "Anforderungen der modernen Softwareentwicklung anpassen.")
