TITEL = "3.4.1 Künstliche Intelligenz (Try)"

CONTENT = ("Das Modul Künstliche Intelligenz behandelt sowohl theoretische Grundlagen (Bayes-Statistik, "
           "Machine Learning, Neuronale Netze) als auch praktische Anwendungen (Agenten-Programmierung, "
           "Implementierung von Algorithmen). Die Verbindung zwischen Theorie und Praxis ist hier besonders "
           "eng, da moderne KI-Anwendungen direkt auf theoretischen Konzepten basieren.\n\n"
           "Aus Studierendensicht wird die Analyse des Verhältnisses von Bayes-Statistik (Theorie) zu "
           "Agenten-Programmierung (Praxis) als relevant empfunden, aber es wird kritisch gesehen, dass der "
           "Fokus möglicherweise zu sehr auf theoretischen Konzepten liegt. Studierende wünschen sich mehr "
           "praktische Erfahrungen mit modernen KI-Frameworks und -Tools.\n\n"
           "Die Herausforderung liegt darin, komplexe theoretische Konzepte in nachvollziehbare, praktisch "
           "anwendbare Kompetenzen zu übersetzen. Während Bayes-Statistik und mathematische Grundlagen wichtig "
           "sind, sollten sie durch praktische Anwendungen mit Frameworks wie TensorFlow, PyTorch oder scikit-learn "
           "ergänzt werden.\n\n"
           "Studierende würden von Projekten profitieren, die zeigen, wie theoretische Konzepte in praktische "
           "Lösungen übersetzt werden. Die Erfahrung mit realen Datensätzen und modernen Tools wäre wertvoller "
           "als rein theoretische Betrachtungen.\n\n"
           "Bewertung: Das Modul vermittelt wichtige Grundlagen, benötigt aber stärkeren Fokus auf praktische "
           "Anwendungen mit modernen Tools. Empfehlung: Try – mehr praktische Übungen mit KI-Frameworks, "
           "Projekte mit realen Datensätzen, stärkere Verbindung zwischen Theorie und Praxis.")
