TITEL = "3.2.3 Datenbanken (Try)"

CONTENT = ("Das Datenbanken-Modul ist stark praxisorientiert und vermittelt sowohl theoretische Grundlagen "
           "(Normalisierung, relationale Algebra, Transaktionen) als auch praktische Kompetenzen (SQL, "
           "Datenbankdesign, Datenbankmanagementsysteme). Studierende arbeiten mit realen DBMS und entwickeln "
           "praktische Projekte.\n\n"
           "Aus Studierendensicht wird der Wunsch nach mehr Fokus auf NoSQL-Konzepte neben der klassischen "
           "relationalen Algebra geäußert. Moderne Anwendungen nutzen zunehmend NoSQL-Datenbanken (MongoDB, "
           "Redis, Cassandra), und Studierende wünschen sich, diese Technologien bereits im Studium kennenzulernen.\n\n"
           "Die theoretischen Grundlagen (Normalisierung, ACID-Prinzipien) bleiben wichtig, sollten aber durch "
           "praktische Erfahrungen mit verschiedenen Datenbankparadigmen ergänzt werden. Ein Vergleich zwischen "
           "relationalen und NoSQL-Datenbanken könnte helfen, die Vor- und Nachteile verschiedener Ansätze zu "
           "verstehen und fundierte Entscheidungen in der Praxis zu treffen.\n\n"
           "Die Balance zwischen Theorie und Praxis gelingt grundsätzlich gut, könnte aber durch die Integration "
           "moderner Datenbanktechnologien noch verbessert werden. Studierende würden von praktischen Projekten "
           "profitieren, die verschiedene Datenbanktypen nutzen.\n\n"
           "Bewertung: Das Modul ist grundsätzlich gut, benötigt aber Anpassungen an moderne Entwicklungen. "
           "Empfehlung: Try – Integration von NoSQL-Konzepten, Erweiterung um praktische Vergleiche verschiedener "
           "Datenbankparadigmen.")
