TITEL = "3.2.6 Paradigmen der Programmierung (Try)"

CONTENT = ("Das Modul Paradigmen der Programmierung behandelt verschiedene Programmierparadigmen, insbesondere "
           "funktionale und objektorientierte Programmierung. Studierende lernen, wie verschiedene Paradigmen "
           "verschiedene Problemstellungen unterschiedlich gut lösen können.\n\n"
           "Aus Studierendensicht wird der Vergleich von funktionaler vs. objektorientierter Programmierung in "
           "der Praxis als wertvoll empfunden. Allerdings wird kritisch gesehen, dass der Fokus möglicherweise "
           "zu sehr auf theoretischen Konzepten liegt und der praktische Nutzen in modernen Entwicklungsumgebungen "
           "nicht immer deutlich wird.\n\n"
           "Die Herausforderung liegt darin, zu zeigen, wie verschiedene Paradigmen in der Praxis eingesetzt "
           "werden. Während objektorientierte Programmierung in Java oder C++ gut etabliert ist, wird funktionale "
           "Programmierung oft als zu abstrakt empfunden. Ein stärkerer Fokus auf moderne Sprachen, die mehrere "
           "Paradigmen unterstützen (wie Python oder JavaScript), könnte den praktischen Nutzen deutlicher machen.\n\n"
           "Studierende würden von praktischen Projekten profitieren, die zeigen, wann welches Paradigma "
           "vorteilhaft ist. Ein Vergleich realer Codebeispiele aus verschiedenen Paradigmen könnte helfen, "
           "die Vor- und Nachteile besser zu verstehen.\n\n"
           "Bewertung: Das Modul vermittelt wichtige Konzepte, benötigt aber stärkeren Praxisbezug. "
           "Empfehlung: Try – mehr Fokus auf praktische Anwendungen, Integration moderner Sprachen, die mehrere "
           "Paradigmen unterstützen.")
