TITEL = "3.3.4 Praxisprojekt mit Seminar (Try)"

CONTENT = ("Das Praxisprojekt mit Seminar ermöglicht es Studierenden, ein größeres Projekt selbstständig zu "
           "planen, durchzuführen und zu reflektieren. Es stellt eine wichtige Vorbereitung auf die "
           "Abschlussarbeit dar und fördert die Fähigkeit, komplexe Probleme eigenständig zu lösen.\n\n"
           "Aus Studierendensicht wird die Reflexion über die Selbstständigkeit bei der Lösung realer Probleme "
           "als wertvoll empfunden, aber es wird kritisch gesehen, dass die Betreuung möglicherweise zu gering "
           "ist. Studierende wünschen sich mehr Unterstützung bei der Projektplanung und -durchführung, "
           "insbesondere wenn Probleme auftreten.\n\n"
           "Die Herausforderung liegt darin, die Balance zwischen Selbstständigkeit und Unterstützung zu finden. "
           "Einerseits soll das Projekt die Fähigkeit zur eigenständigen Problemlösung fördern, andererseits "
           "sollten Studierende nicht überfordert werden. Eine strukturiertere Betreuung mit regelmäßigen "
           "Meilensteinen könnte helfen.\n\n"
           "Besonders wertvoll wäre eine stärkere Verknüpfung mit der Industrie. Wenn Projekte in Kooperation "
           "mit Unternehmen durchgeführt werden, erhalten Studierende direkte Rückmeldung und lernen, wie "
           "professionelle Projekte in der Praxis ablaufen. Dies würde den Transferwert deutlich erhöhen.\n\n"
           "Bewertung: Das Modul ist grundsätzlich gut konzipiert, benötigt aber Verbesserungen bei der "
           "Betreuung und stärkere Praxisorientierung. Empfehlung: Try – strukturiertere Betreuung, mehr "
           "Kooperation mit der Industrie, klarere Meilensteine.")
