TITEL = "3.3.2 Projektmanagement (Try)"

CONTENT = ("Das Modul Projektmanagement behandelt sowohl klassische Methoden (Netzplantechnik, Gantt-Diagramme) "
           "als auch agile Ansätze (Scrum, Kanban). Studierende lernen verschiedene Methoden zur Planung und "
           "Steuerung von Projekten kennen.\n\n"
           "Aus Studierendensicht wird die Bewertung der agilen Methoden (Scrum) vs. klassischer Netzplantechnik "
           "als relevant empfunden, aber es wird kritisch gesehen, dass der Fokus möglicherweise zu gleichmäßig "
           "auf beide Ansätze verteilt ist. In der modernen Softwareentwicklung dominieren agile Methoden, und "
           "Studierende wünschen sich einen stärkeren Fokus auf diese praxisrelevanten Ansätze.\n\n"
           "Die Herausforderung liegt darin, die Balance zwischen theoretischer Vollständigkeit und praktischer "
           "Relevanz zu finden. Während klassische Methoden für bestimmte Projekttypen (z.B. Bauprojekte) "
           "relevant bleiben, sind agile Methoden in der Softwareentwicklung deutlich dominanter. Ein stärkerer "
           "Fokus auf Scrum, Kanban und verwandte Methoden könnte den praktischen Nutzen erhöhen.\n\n"
           "Studierende würden von praktischen Übungen profitieren, in denen sie agile Methoden direkt anwenden "
           "können. Die Erfahrung mit Sprint-Planning, Daily Standups und Retrospektiven wäre wertvoller als "
           "theoretisches Wissen über Netzplantechnik.\n\n"
           "Bewertung: Das Modul vermittelt wichtige Kompetenzen, benötigt aber Anpassung an moderne "
           "Entwicklungspraktiken. Empfehlung: Try – stärkerer Fokus auf agile Methoden, mehr praktische "
           "Übungen, Reduzierung klassischer Methoden auf Grundlagen.")
