TITEL = "Transferfähigkeit in reale Problemstellungen"

CONTENT = ("Ob Studierende lernen, Algorithmen auf konkrete Probleme anzuwenden (nicht nur Klausurwissen)."
            "\n\n"
"Ein häufiger Kritikpunkt ist die starke Fokussierung auf formale Aufgabenstellungen, die wenig Raum für kreative "
           "Problemlösungen lassen. Studierende wünschen sich mehr offene Aufgaben, bei denen sie selbst entscheiden "
           "müssen, welcher algorithmische Ansatz geeignet ist, welche Datenstrukturen sinnvoll sind und welche "
           "Trade-offs (Laufzeit vs. Speicherbedarf, Einfachheit vs. Effizienz) in einem konkreten Szenario"
           " angemessen erscheinen. In der Praxis sind solche Entscheidungen Teil des täglichen Entwicklungsalltags, "
           "insbesondere bei der Arbeit mit großen Datenmengen oder hochperformanten Systemen."
            "\n\n"
"Solche Kompetenzen entsprechen stärker dem realen Berufsalltag, in dem unvollständige Anforderungen, widersprüchliche"
           " Ziele und Ungewissheit die Regel sind. Empirische Arbeiten zur Entwicklung von Problemlöse- und Employability-Skills "
           "unterstreichen, dass projekt- und problemorientierte Lernsettings diese Fähigkeiten deutlich besser fördern als"
           " rein klausurorientierte Formate. Der aktuelle Fokus auf klar definierte Übungsaufgaben fördert "
           "zwar analytische Fähigkeiten und formale Korrektheit, schöpft das Potenzial für Transferkompetenzen jedoch nicht "
           "vollständig aus."
            "\n\n"
"Die Empfehlung lautet daher: Keep der algorithmischen Grundlagen, Try für eine stärkere Ausrichtung auf Transferaufgaben,"
           "projektorientiertes Lernen und reflexive Elemente, in denen Studierende ihre Lösungswege begründen und alternative "
           "Ansätze diskutieren."
)