TITEL = "3.5.4 Szenario: 'Praxis-Duales-Modell' (Try)"

CONTENT = ("Dieses Szenario beschreibt einen Vorschlag für eine engere Verzahnung mit Werkstudententätigkeiten "
           "und praktischen Erfahrungen während des Studiums. Es zeigt, wie das Curriculum stärker mit der "
           "Industrie verzahnt werden könnte, um den Anwendungsbezug zu erhöhen.\n\n"
           "Im 'Praxis-Duales-Modell' würden Studierende die Möglichkeit haben, Werkstudententätigkeiten oder "
           "Praktika stärker in ihr Studium zu integrieren. Theoretische Module könnten durch praktische "
           "Erfahrungen ergänzt werden, und umgekehrt könnten praktische Projekte theoretische Konzepte "
           "verdeutlichen.\n\n"
           "Das Szenario könnte durch flexible Studienpläne umgesetzt werden, die es Studierenden ermöglichen, "
           "Module in Abhängigkeit von ihren praktischen Erfahrungen zu belegen. Studierende könnten "
           "beispielsweise nach einem Praktikum Module wählen, die ihre praktischen Erfahrungen vertiefen.\n\n"
           "Besonders wertvoll wäre eine stärkere Kooperation mit Unternehmen, die Werkstudentenstellen anbieten. "
           "Studierende könnten ihre praktischen Erfahrungen direkt in ihr Studium einbringen und umgekehrt "
           "theoretisches Wissen in der Praxis anwenden.\n\n"
           "Die Herausforderung liegt darin, sicherzustellen, dass auch in diesem Szenario die theoretischen "
           "Grundlagen nicht zu kurz kommen. Praktische Erfahrungen sollten theoretisches Wissen ergänzen, "
           "nicht ersetzen.\n\n"
           "Dieses Szenario zeigt, wie eine stärkere Verzahnung mit der Industrie den Anwendungsbezug erhöhen "
           "könnte. Empfehlung: Try – als Option für praxisorientierte Studierende, die bereits während des "
           "Studiums Berufserfahrung sammeln möchten.")
