TITEL = "3.5.1 Team-Divergenz: Mathe-Hürde (Subjektiv)"

CONTENT = ("Dieser Knoten dokumentiert unterschiedliche Meinungen im Team zum Nutzwert der harten Theorie, "
           "insbesondere der Mathematik-Module. Die Diskussion zeigt, dass die optimale Balance zwischen Theorie "
           "und Praxis nicht objektiv bestimmbar ist, sondern von individuellen Erfahrungen, Vorerfahrungen und "
           "Karrierezielen abhängt.\n\n"
           "Einige Teammitglieder sehen Mathematik als notwendige Hürde, die überwunden werden muss, aber deren "
           "praktischer Nutzen sich erst später erschließt. Sie argumentieren, dass mathematische Denkweisen "
           "wichtig sind, auch wenn der konkrete Stoff nicht immer direkt anwendbar ist.\n\n"
           "Andere Teammitglieder kritisieren, dass der Mathematik-Anteil zu hoch ist und zu wenig Bezug zur "
           "praktischen Informatik hat. Sie wünschen sich eine stärkere Fokussierung auf mathematische Konzepte, "
           "die direkt in der Informatik angewendet werden, und weniger abstrakte Mathematik.\n\n"
           "Die Diskussion zeigt, dass unterschiedliche Studierende unterschiedliche Bedürfnisse haben. "
           "Studierende mit stärkerer mathematischer Vorerfahrung sehen den Nutzen eher, während praxisorientierte "
           "Studierende den Bezug vermissen. Eine differenzierte Betrachtung könnte helfen, beide Gruppen besser "
           "zu bedienen.\n\n"
           "Diese subjektive Perspektive ist wichtig, da sie zeigt, dass die optimale Balance zwischen Theorie "
           "und Praxis nicht für alle Studierenden gleich ist. Eine erfolgreiche Studiengangsgestaltung sollte "
           "diese unterschiedlichen Bedürfnisse berücksichtigen.")
